import sys
import os
import json
import time
import uuid
from pathlib import Path
from qdrant_client import QdrantClient, models
from tqdm import tqdm

# Adds the project root directory directly to Python's search path
root_dir = Path(__file__).resolve().parent.parent
sys.path.append(str(root_dir))

from settings import settings

# ==============================================================================
# CONFIGURATION
# ==============================================================================
LOCAL_QDRANT_URL = "http://localhost:6333"
BATCH_SIZE = 100
MAX_RETRIES = 5  # Maximum number of retry attempts for write operations

# ── WORKFLOW TOGGLE ────────────────────────────────────────────────────────────
# UPDATE_MODE = True  : INCREMENTAL PATCH. Processes removal.json, then upserts 
#                       new/updated chunks from local dB without dropping cloud schema.
# UPDATE_MODE = False : FULL REBUILD. Drops the entire cloud collection, skips 
#                       removal.json, and streams the entire local dB to cloud.
UPDATE_MODE = True 

# Path to the removal file generated by chunks_diff.py
# Adjust this path based on where you place the file before running this script
DELETION_DIR = Path(__file__).resolve().parent
removal_file = sorted(DELETION_DIR.glob("removal_*.json"))[-1] # sorted() because if any older removal.json exists, we need the most latest one by date in name


def process_deletions(cloud_client: QdrantClient, target_collections: list):
    """
    PHASE 1: THE PRUNING PHASE
    Executes targeted deletions on the Cloud database using removal.json.
    This MUST happen before upserts so we don't accidentally delete freshly updated chunks.
    """
    if not os.path.exists(removal_file):
        print(f"   ℹ️  No removal file found at '{removal_file}'. Skipping deletions.")
        return

    print(f"   🗑️  Loading deletion targets from '{removal_file}'...")
    try:
        with open(removal_file, "r", encoding="utf-8") as f:
            ids_to_remove = json.load(f)
    except Exception as e:
        print(f"   ❌ Failed to read removal file: {e}")
        sys.exit(1)

    if not ids_to_remove:
        print("   ℹ️  Removal file is empty. Skipping deletions.")
        return

    print(f"   🎯 Found {len(ids_to_remove):,} unique IDs to purge from Cloud.")
    
    # IDs in our pipeline are globally unique deterministic UUIDs. 
    # Because removal.json contains both parent and child IDs mixed together, 
    # we safely fire the delete command at all target collections. Qdrant will 
    # simply ignore IDs that don't exist in a specific collection.
    
    # removal.json contains raw chunk string IDs (e.g. "langchain_src_foo_bar_intro").
    # Qdrant stores points using UUID5 of those strings — same conversion used
    # in the indexing pipeline. Convert before deletion or Qdrant returns 400.
    def to_uuid(raw_id: str) -> str:
        return str(uuid.uuid5(uuid.NAMESPACE_DNS, raw_id.strip()))

    uuid_ids = [to_uuid(x) for x in ids_to_remove if x]
    print(f"   🔑 Converted {len(uuid_ids):,} raw IDs → UUID5 format.")

    # Batch deletions to avoid payload size limits
    batch_size = 500
    for i in range(0, len(uuid_ids), batch_size):
        batch = uuid_ids[i : i + batch_size]
        for collection in target_collections:
            if cloud_client.collection_exists(collection):
                try:
                    cloud_client.delete(
                        collection_name=collection,
                        points_selector=models.PointIdsList(points=batch),
                    )
                except Exception as e:
                    print(f"   ❌ Failed to delete batch {i}–{i+len(batch)} from {collection}: {e}")
                    raise e
        print(f"      ✅ Batch {i}–{i+len(batch)} deleted from all collections.")
    print("   ✅ Cloud deletion phase complete.\n")


def migrate_database():
    # ==============================================================================
    # PHASE 0: INITIALIZATION
    # ==============================================================================
    print(f"🔌 Connecting to instances (UPDATE_MODE={UPDATE_MODE})...")
    local_client = QdrantClient(url=LOCAL_QDRANT_URL)    

    cloud_client = QdrantClient(
        url = settings.QDRANT_CLOUD_CLUSTER_ENDPOINT.get_secret_value(),
        api_key = settings.QDRANT_CLOUD_KEY.get_secret_value(),
        timeout = 120.0) # Elevated timeout to prevent batch timeouts on heavy payloads

    try:
        collections = [c.name for c in local_client.get_collections().collections]
        print(f"📦 Found local collections to process: {collections}\n")
    except Exception as e:
        print(f"❌ Failed to connect to local Qdrant. Is Docker running? Error: {e}")
        sys.exit(1)

    # ==============================================================================
    # PHASE 1: PRUNING (Only applicable in UPDATE_MODE)
    # ==============================================================================
    if UPDATE_MODE:
        print("═" * 70)
        print("🧹 PHASE 1: EXECUTING CLOUD DELETIONS")
        print("═" * 70)
        process_deletions(cloud_client, collections)
    else:
        print("⚠️  FULL REBUILD MODE: Skipping targeted deletions (collections will be dropped entirely).")


    # ==============================================================================
    # PHASE 2: SCHEMA SYNC & STREAMING
    # ==============================================================================
    for collection_name in collections:
        print("═" * 70)
        print(f"🔄 PHASE 2: PROCESSING '{collection_name}'")
        print("═" * 70)
        
        # Fetch local configuration and exact total point count from the ephemeral local dB
        local_info = local_client.get_collection(collection_name)
        total_points = local_info.points_count
        print(f"   📊 Points in local staging database to upload: {total_points:,}")
        
        collection_exists = cloud_client.collection_exists(collection_name)     
        
        # ── Schema Management ────────────────────────────────────────────────────
        if collection_exists and UPDATE_MODE:
            print(f"   ⏩ UPDATE MODE: Collection '{collection_name}' exists on Cloud. Preserving schema.")
        else:
            if collection_exists:
                print(f"   ⚠️  REBUILD MODE: Dropping existing cloud collection '{collection_name}'...")
                cloud_client.delete_collection(collection_name)

            print("   🏗️ Creating collection schema on Qdrant Cloud...")

            cloud_params = local_info.config.params
            cloud_optimizer = local_info.config.optimizer_config
            
            # PERFORMANCE SHIELD: Temporarily disable background indexing threads 
            # during an initial massive bulk migration to maximize upload bandwidth.
            if not UPDATE_MODE:
                cloud_optimizer = models.OptimizersConfigDiff(indexing_threshold=0)

            cloud_client.create_collection( 
                collection_name       = collection_name,
                vectors_config        = cloud_params.vectors,
                sparse_vectors_config = cloud_params.sparse_vectors,
                quantization_config   = local_info.config.quantization_config,
                optimizers_config     = cloud_optimizer)

            # Block until cloud confirms the collection is fully allocated
            while cloud_client.get_collection(collection_name).status != models.CollectionStatus.GREEN:
                time.sleep(0.5)
            print("   ✅ Base collection schema created on cloud.")            

            # Replicate Payload Indexes (Required for metadata filtering)
            if local_info.payload_schema:
                print("   🔍 Replicating local payload keyword indexes...")
                for field_name, schema_info in local_info.payload_schema.items():
                    data_type_value = schema_info.data_type                    

                    if "text" in str(data_type_value).lower():
                        text_params = getattr(schema_info, 'params', None)                       
                        tokenizer_val = getattr(text_params, 'tokenizer', models.TokenizerType.WORD)
                        if hasattr(tokenizer_val, 'value'):
                            tokenizer_val = tokenizer_val.value                            

                        safe_field_schema = models.TextIndexParams(
                            type=models.TextIndexType.TEXT,
                            tokenizer=models.TokenizerType(tokenizer_val),
                            lowercase=getattr(text_params, 'lowercase', True),
                            min_token_len=getattr(text_params, 'min_token_len', None),
                            max_token_len=getattr(text_params, 'max_token_len', None)
                        ) if text_params else models.PayloadSchemaType.TEXT
                    else:
                        raw_enum_val = data_type_value.value if hasattr(data_type_value, 'value') else data_type_value
                        safe_field_schema = models.PayloadSchemaType(raw_enum_val)
                        
                    cloud_client.create_payload_index(
                        collection_name = collection_name,
                        field_name      = field_name,
                        field_schema    = safe_field_schema)
                print("   ✅ Payload indexing replication complete.")
        
        # ── Data Streaming (Additions/Updates) ───────────────────────────────────
        if total_points == 0:
            print(f"   ℹ️  Local '{collection_name}' is empty (no updates). Skipping stream.\n")
            continue
            
        next_page_offset = None
        action_text = "Upserting" if (collection_exists and UPDATE_MODE) else "Uploading"
        print(f"   🚀 Starting live data stream to Cloud...")        

        with tqdm(total=total_points, desc=f"   {action_text} '{collection_name}'", unit="point") as pbar:
            while True: 
                # Paginate through the ephemeral local database
                records, next_page_offset = local_client.scroll(
                    collection_name = collection_name,
                    limit           = BATCH_SIZE,
                    offset          = next_page_offset,
                    with_payload    = True,    
                    with_vectors    = True)                

                if not records:
                    break

                points_to_upload = []
                for record in records:
                    normalized_vector = {}
                    if isinstance(record.vector, dict):
                        for v_name, v_data in record.vector.items():
                            # Re-serialize sparse vectors into the exact format the Qdrant SDK expects
                            if hasattr(v_data, "indices") and hasattr(v_data, "values"):
                                normalized_vector[v_name] = models.SparseVector(indices=list(v_data.indices), values=list(v_data.values))
                            elif hasattr(v_data, "tolist"):
                                normalized_vector[v_name] = v_data.tolist()
                            else:
                                normalized_vector[v_name] = v_data
                    else:
                        normalized_vector = record.vector.tolist() if hasattr(record.vector, "tolist") else record.vector

                    points_to_upload.append(models.PointStruct(
                            id=record.id,
                            vector=normalized_vector,
                            payload=record.payload))                

                # Cloud Upsert block with Exponential Backoff
                for attempt in range(1, MAX_RETRIES + 1):
                    try:
                        cloud_client.upsert(
                            collection_name=collection_name,
                            points=points_to_upload
                        )
                        break
                    except Exception as e:
                        if attempt == MAX_RETRIES:
                            print(f"\n❌ Permanent failure on upsert after {MAX_RETRIES} attempts.")
                            raise e
                        sleep_time = attempt * 2
                        time.sleep(sleep_time)               

                pbar.update(len(points_to_upload))                

                if next_page_offset is None:
                    break                    

        # ── Optimizer Restoration ────────────────────────────────────────────────
        if not UPDATE_MODE:
            print("   🛠️ Re-enabling background indexing thresholds for optimal cloud search speeds...")
            cloud_client.update_collection(
                collection_name=collection_name,
                optimizer_config=models.OptimizersConfigDiff(indexing_threshold=20000))
            print("   ✅ Cloud indices optimization triggered successfully.")            

        print(f"✅ Finished processing collection: '{collection_name}'\n")

    print("🎉 Full synchronization process finished successfully!")

if __name__ == "__main__":
    migrate_database()